CREATE DATABASE NEWS_PORTAL_NODEJS;

USE NEWS_PORTAL_NODEJS;

CREATE TABLE NEWS(
	ID INT NOT NULL AUTO_INCREMENT,
	TITLE VARCHAR(100),
	NEWS TEXT,
	DATA_CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(ID)
);

DESCRIBE NEWS;

INSERT INTO NEWS(TITLE,NEWS) VALUES('My Title','content of the news');

SELECT * FROM NEWS;